version: '2'

services:
        mongo:
            image: mongo:3.6
            restart: always
            container_name: mongo
            ports:
                - "27017:27017"
            volumes:
                - ./data/mongo:/data/db

        mongo-express:
            container_name: mongo-express
            image: mongo-express
            ports:
                - "8081:8081"
            links:
                - "mongo:mongo"